---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Si los ponemos en cada subclase, tendremos mucho código repetido
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Si los ponemos en `Unidad`, le estaremos agregando a ciertas clases métodos
    que no le corresponden
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Si introducimos clases abstractas intermedias, el código resultará engorroso
  checked: true
name: Una jerarquía complicada
