---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: |+
  ¡Perfecto! De todas formas, dado que obviamente la primera forma que vimos (`def objeto.metodo`) es mas compacta que la de autoclases, la preferiremos siempre que se pueda. Sólo que ahora ya sabés que es lo que realmente está sucediendo. O casi...



manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Para declarar métodos en un mixin
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Para declarar métodos en una clase
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Para declarar autométodos, en una instancia (que en definitiva son métodos
    de la autoclase)
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Para declarar métodos de la autoclase
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Para declarar clases
  checked: true
name: Autoclases
